### ISSUE TITLE
Error when creating quantile agent for using CQL for Atari

### ISSUE THREAD

**Issue by timo-sievernich** [aviralkumar2907/CQL#1]
Hi Aviral,

when I tried to run the 'train.py' script for Atari games, I noticed an error when creating the quantile agent in 'atari/batch_rl/multi_head/quantile_agent.py':  In line 117 you are passing the argument "minq_weight" into the init function of the rainbow agent, but this class has no argument "minq_weight". After I deleted the argument the code runs perfectly.  

Best,
Timo

**Comment by aviralkumar2907** [comment]
Hi Timo,

I guess I added it to the rainbow agent in dopamine when running locally, but unfortunately, that is not a part of this repo. I will fix that.

Thanks,
Aviral

**Comment by JayanthRR** [comment]
Hi Aviral,

Is this fixed yet? 

Thanks,
Jayanth.
