### ISSUE TITLE
code bugs

### ISSUE THREAD

**Issue by rainbow979** [aviralkumar2907/CQL#10]
https://github.com/aviralkumar2907/CQL/blob/d67dbe9cf5d2b96e3b462b6146f249b3d6569796/d4rl/rlkit/torch/sac/cql.py#L241
`q1_next_actions = self._get_tensor_values(obs, new_curr_actions_tensor, network=self.qf1)` is wrong.
It should be `q1_next_actions = self._get_tensor_values(next_obs, new_curr_actions_tensor, network=self.qf1)`

**Comment by zhihanyang2022** [comment]
Please check out Aviral's last comment to this closed issue: https://github.com/aviralkumar2907/CQL/issues/4. It's confusing for sure (confused me too) but it turns out to be correct.

**Comment by rainbow979** [comment]
OK. Thanks a lot.
