### ISSUE TITLE
ImportError: cannot import name 'elem_or_tuple_to_numpy' from 'rlkit.torch.core'

### ISSUE THREAD

**Issue by HYDesmondLiu** [aviralkumar2907/CQL#15]
When I tried to run d4rl MuJoCo benchmark, this happens.
 It looks like there is a version discrepancy of rlkit library between the published code and the real one used in the paper. 
If updating the code bothers you, maybe you could give a pointer to me about which rlkit version is used in your experiments? Or, where can I download the rlkit library you used in the experiments? 

`cql_mujoco_new.py:124: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (gpu_str is not ""):
No personal conf_private.py found.
doodad not detected
Traceback (most recent call last):
  File "cql_mujoco_new.py", line 6, in <module>
    from rlkit.torch.sac.policies import TanhGaussianPolicy, MakeDeterministic
  File "/home/hsinyu/rlkit/rlkit/torch/sac/policies/__init__.py", line 1, in <module>
    from rlkit.torch.sac.policies.base import (
  File "/home/hsinyu/rlkit/rlkit/torch/sac/policies/base.py", line 11, in <module>
    from rlkit.torch.core import torch_ify, elem_or_tuple_to_numpy
ImportError: cannot import name 'elem_or_tuple_to_numpy' from 'rlkit.torch.core' (/home/hsinyu/rlkit/rlkit/torch/core.py)`

**Comment by HYDesmondLiu** [comment]
Solved on my own.

**Comment by scey26** [comment]
@HYDesmondLiu
Hello? I have the same problem. Could you tell me how you solve it? Thanks!

**Comment by HYDesmondLiu** [comment]
> @HYDesmondLiu Hello? I have the same problem. Could you tell me how you solve it? Thanks!

I cannot remember the details, I think I downloaded another rlkit version somewhere with this function.
