### ISSUE TITLE
Logsumexp calculation in CQL(H) for continuous action space

### ISSUE THREAD

**Issue by zhihanyang2022** [aviralkumar2907/CQL#7]
Hi Aviral,

Thanks for sharing your code!

My concern is about logsumexp calculation in CQL(H) for D4RL. On page 29 of your paper, you mentioned your technique for computing logsumexp, which looks fine to me. However, the code seems to be a bit different in a number of ways:

1. $N=20$ rather than 10 for the current policy, which is ok (i.e., not a bug).
2. Following my derivation based on your derivation on page 29, you seem to forget to multiply by $2N_1$ and $2N_2$ in your code (cql.py, line 263 to 271). In your code, you simply plugged in the log probabilities without doing the multiplication first. Is this a bug? 

Also, a perhaps unrelated question: How did you come up with this way of computing logsumexp? Splitting the sum into two separate expectations (instead of just using one) w.r.t. two different distributions is not so intuitive for me.

![image](https://user-images.githubusercontent.com/43589364/102847505-7588c400-444d-11eb-914c-de3efce8ddf1.png)

**Comment by zhihanyang2022** [comment]
Eventually, I figured out that we can factor out $N_1$ and $N_2$ (the following derivation assumes they are equal):

![image](https://user-images.githubusercontent.com/43589364/103114661-7e220a00-469a-11eb-8e93-010a9830f0c4.png)

**Comment by dbsxdbsx** [comment]
Hi @zhihanyang2022, could you explain a little for :
1. why use two different distributions? I am at a loss here,too. And I think just sample 10 actions from a pure uniform distribution is correct.
2. even following the equation in p29,  why does the code concatenate both `q1_curr_actions` and `q1_next_actions` [here](https://github.com/aviralkumar2907/CQL/blob/master/d4rl/rlkit/torch/sac/cql.py);
